sudo: required
services: 
  - docker
  
before_install: 
  - mvn clean install
  - docker build -t chowju1983/sample-docker-app -f Dockerfile . 
  
script: 
  - docker run chowju1983/sample-docker-app 
  
  
  