sudo: required
services: 
  - docker
  
before_install: 
  - mvn clean install
  - docker build -t chowju1983/sample-docker-app -f Dockerfile . 

deploy: 
  provider: elasticbeanstock
  region: "us-east-1"
  app: "sample-docker-app"
  env: "SampleDockerApp-env"
  bucket-name: "elasticbeanstalk-us-east-1-326359242220" 
  bucket_path: "sample-docker-app"
  access_key_id: $ACCESS_KEY
  secret_access-key: 
    secure: "$SECRET_ACCESS_KEY"
  